Nowe pliki

diff --git a/workflows/01-building-blocks.yaml b/workflows/01-building-blocks.yaml
--- a/workflows/01-building-blocks.yaml
+++ b/workflows/01-building-blocks.yaml
@@ -1,8 +1,22 @@
 ```yaml
-steps:
-  - name: Multi-line bash
-    run: |
-      echo "Jestem"
-      echo "wieloliniowym"
-      echo "skryptem."
-```
+name: 01 - Build Blocks
+
+on:
+  workflow_dispatch:
+
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail now"
+          exit 1
+      - name: Say Goodbye
+        run: |
+          echo "This step will be skipped if the previous step fails"
